# Applications of derivatives

## Critical points

$f'(x) = 0$ ou $f'(x) = \nexists$ ou indefinido

## Maximum, minimum, and inflection points

Ponto de mínimo (convexidade $\bigcup$ ) $\rightarrow f''(x) > 0 \ \forall x \in \ ]a, b[$

Ponto de máximo (concavidade $\bigcap$ ) $\rightarrow f''(x) < 0 \ \forall x \in \ ]a, b[$

Ponto de inflexão $\rightarrow f''(x) = 0 \ \forall x \in \ ]a, b[$

## Full study of a function

1. Determinação do domínio.
2. Determinação das intersecções com os eixos, quando possível/
3. Determinação dos intervalos de crescimento e decrescimento e de possíveis pontos de máximo e mínimo.
4. Determinação dos intervalos em que a função é côncava para cima ou para baixo e de possíveis pontos de inﬂexão.
5. Determinação dos limites nos extremos do domínio e de possíveis assíntotas.
6. Determinação dos limites laterais nos pontos de descontinuidades (quando houver e possíveis assíntotas).

## Financial/administrative functions

* $R(P \ ou \ Q) = P \times Q$
* $L(P \ ou \ Q) = R(P \ ou \ Q) - C (P \ ou \ Q)$
* $C_{mg}(x) = C'(x)$, normalmente $\Delta x = 1$
* $R_{mg}(x) = R'(x)$, normalmente $\Delta x = 1$
* Prop. marginal a consumir (C) $\rightarrow p^{c}_{mg} = C'(y)$, $y =$ renda disponível
* Prop. marginal a poupar (S) $\rightarrow  p^{c}_{mg} = S'(y)$, $y =$ renda disponível
* Produtividade marginal $\rightarrow P_{mg}(x) = P'(x)$

## Elasticity - Supply and Demand Function

* Função Demanda $\rightarrow \cfrac{dx}{dp} < 0$
* Função Oferta $\rightarrow \cfrac{dx}{dp} > 0$
* Ponto de Equilíbrio $\rightarrow p_{d} = p_{o}$
* variação percentual no preço $= \cfrac{\Delta p}{p_{0}}$
* Variação percentual na quantidade $= \cfrac{\Delta x}{x_{0}}$ 
* $e = \begin{vmatrix} \lim \limits_{\Delta p \to 0} \cfrac{\cfrac{\Delta x}{x_{0}}}{\cfrac{\Delta p}{p_{0}}} \end{vmatrix} = \cfrac{p_{0}}{x_{0}} \times \begin{vmatrix} \lim \limits_{\Delta p \to 0} \cfrac{\Delta x}{\Delta p}\end{vmatrix} = \cfrac{p_{0}}{x_{0}} \times \begin{vmatrix} \cfrac{dx}{dp}\end{vmatrix}$
* $e > 1 \rightarrow$ elástica, $0 < e > 1 \rightarrow$ inelástica, $e = 1 \rightarrow$ elasticidade unitária
    
    \* Não se aplica em caso de elasticidade cruzada.
