# Series

## Tests for convergence of inﬁnite series

> Reference: @hass2018

1. __The nth-Term Test__: Unless $a_{n} \to 0$, the series diverges.
2. __Geometric series__: $\sum ar^{n}$ converges if $|r| < 1$; otherwise it diverges.
3. __p-series__: $\sum \cfrac{1}{n^{p}}$ converges if $p > 1$l otherwise it diverges.
4. __Series with nonnegative terms__: Try the Integral Test, Ratio Test, or Root Test. Try comparing to a known series with the Comparison Test or the Limit Comparison Test.
5. __Series with some negative terms__: Does $\sum | a_{n} |$ converge? If yes, so does $\sum a_{ n}$ because absolute convergence implies convergence.
6. __Alternating series__: $\sum a_{n}$ converges if the series satisﬁes the conditions of the Alternating Series Test.

## Taylor series

> Reference: @hase2022

Let $f$ be a function that has all the “required” derivatives. One can demand its behavior in the neighborhood of a point, $x_{0}$. In this case, it is possible to approximate $f$ with a polynomial (around $x_{0}$), which is the Taylor series. Concretely, one has

$$
f(x) = a_{0} + a_{1}(x - x_{0}) + a_{2}(x - x_{0})^{2} + a_{3}(x - x_{0})^{3} + \cdots + a_{n}(x - x_{0})^{n} + \cdots
\tag{1}
$$

which is a polynomial representation in $(x - x_{0})$. Note that, intuitively, if the distance between $x$ and $x_{0}$ becomes small, the terms of this series decrease, _a priori_, with $n$. The goal of this section is the determination of the set of coefficients $\{a_{n}\}$.

1. Show, by imposing $x = x_{0}$ in $(1)$, that $a_{0} = f(x_{0})$. 

2. Determine $f′(x)$. Show, by imposing $x = x_{0}$ in the resultant equation, that $a_{1} = \cfrac{1}{1!} f′(x_{0})$.

Denote by $\cfrac{d^{2}}{dx^{2}} f(x)$, or $f′′(x)$, or $f^{(2)}(x)$, the second order derivative of $f$. This symbol stands for

$$
\cfrac{d^{2}}{dx^{2}} f(x) = \cfrac{d}{dx} \left [ \cfrac{d}{dx} f(x) \right ]
\tag{2}
$$

Exemplifying, if $g(x) = \sin x$, then $g′(x) = \cos x$ and $g′′(x) = − \sin x$. Analogously,

$$
\cfrac{d^{3}}{dx^{3}} f(x) = \cfrac{d}{dx} \left [ \cfrac{d^{2}}{dx^{2}} f(x) \right ] = \cfrac{d}{dx} \left [ \cfrac{d}{dx} \left [ \cfrac{d}{dx} f(x) \right ] \right ] \quad , \quad \cfrac{d^{4}}{dx^{4}} f(x) = \cfrac{d}{dx} \left [ \cfrac{d^{3}}{dx^{3}} f(x) \right ] \cdots, \quad et \ cætera
\tag{3}
$$

Furthermore, for $g(x) = \sin x$, one has $g^{(3)} (x) = − \cos x$, $g^{(4)} (x) = \sin x$, _et cætera_.

3. Determine $f′′(x)$. Show, by imposing $x = x_{0}$ in the resultant equation, that $a_{2} = \cfrac{1}{2!} f′′(x_{0})$.

4. Determine $f^{(3)} (x)$. Show, by imposing $x = x_{0}$ in the resultant equation, that $a_{3} = \cfrac{1}{3!} f^{(3)} (x_{0})$. 

5. Show that $a_{n} = \cfrac{1}{n!} f^{(n)} (x_{0})$. 

In other words, if the series exists, one has

$$
f(x) = \sum \limits^{\infty}_{n = 0} \cfrac{1}{n!} f^{(n)} (x_{0}) (x - x_{0})^{n}
$$

## Maclaurin series

> Reference: @hass2018

A Maclaurin series is a Taylor series where $x_{0} = 0$.

* $\cfrac{1}{1 - x} = 1 + x + x^2 + \cdots + x^{n} + \cdots = \sum \limits^{\infty}_{n = 0} x^{n}, \quad |x| < 1$

* $\cfrac{1}{1 + x} = 1 - x + x^2 - \cdots + (- x^{n}) + \cdots = \sum \limits^{\infty}_{n = 0} (-1)^{n} x^{n}, \quad |x| < 1$

* $e^{x} = 1 + x + \cfrac{x^{2}}{2!} + \cdots + \cfrac{x^{n}}{n!} + \cdots = \sum \limits^{\infty}_{n = 0} \cfrac{x^{n}}{n!}, \quad |x| < \infty$

* $\sin x = x - \cfrac{x^{3}}{3!} + \cfrac{x^{5}}{5!} - \cdots + (-1)^{n} \cfrac{x^{2n + 1}}{(2n +1)!} + \cdots = \sum \limits^{\infty}_{n = 0} \cfrac{(-1)^{n} x^{2n + 1}}{(2n +1)!}, \quad |x| < \infty$

* $\cos x = 1 - \cfrac{x^{2}}{2!} + \cfrac{x^{4}}{4!} - \cdots + (-1)^{n} \cfrac{x^{2n}}{(2n)!} + \cdots = \sum \limits^{\infty}_{n = 0} \cfrac{(-1)^{n} x^{2n}}{(2n)!}, \quad |x| < \infty$

* $\ln (1 + x) = x - \cfrac{x^{2}}{2} + \cfrac{x^{3}}{3} - \cdots + (-1)^{n - 1} \cfrac{x^{n}}{n} + \cdots = \sum \limits^{\infty}_{n = 1} \cfrac{(-1)^{n - 1} x^{n}}{n}, \quad -1 < x \leq 1$

* $\ln \cfrac{1 + x}{1 - x} = 2 \tanh^{-1} x = 2 \left ( x + \cfrac{x^{3}}{3} + \cfrac{x^{5}}{5} + \cdots + \cfrac{x^{2n + 1}}{2n + 1} + \cdots \right ) = 2 \sum \limits_{n = 0}^{\infty} \cfrac{x^{2n + 1}}{2n - 1}, \quad |x| < 1$

* $\tan^{-1} x = x - \cfrac{x^{3}}{3} + \cfrac{x^{5}}{5} - \cdots + (- 1)^{n} \cfrac{x^{2n + 1}}{2n + 1} + \cdots = \sum \limits^{\infty}_{n = 0} \cfrac{(- 1)^{n} x^{2n + 1}}{2n + 1}, \quad |x| \leq 1$

## Binomial series

> Reference: @hass2018

$$
(1 + x)^{m} = 
1 + mx + \cfrac{m (m - 1) x^{2}}{2!} + \cfrac{m (m - 1) (m - 2) x^{3}}{3!} + 
\cdots +
$$

$$
+ \cfrac{m (m - 1) (m - 2) \cdots (m - k + 1) x^{k}}{k!} + \cdots = 
1 + \sum \limits^{\infty}_{k = 1} \binom{m}{k} x^{k}, \quad |x| < 1
$$

Where

$$
\binom{m}{1} = m, \quad \binom{m}{2} = \cfrac{m (m - 1)}{2!}, \quad \binom{m}{k} = \cfrac{m (m - 1) \cdots (m - k + 1)}{k!} \quad \text{for} \ k \geq 3
$$

## Big "Oh" notation

> Reference: @hase2022

For $x \ll 1$, expanding $f(x) = \sin x$ aroung $x_{0}$ leads to

$$
\sin x = x - \cfrac{x^{3}}{3!} + \cfrac{x^{5}}{5!} - \cfrac{x^{7}}{7!} + \cdots
$$

The term in the series above decreases with its order. The series can also be represented by

$$
\sin x = x - \cfrac{x^{3}}{3!} + \cfrac{x^{5}}{5!} - \cfrac{x^{7}}{7!} + \mathcal{O} (x^{9})
$$

where $\mathcal{O} (x^{9})$ stands for contributions of order $x^{9}$ (_id est_, proportional to $x^{6}$) __or less__, since the absolute value of the remaining
terms $\left | \cfrac{x^{9}}{9!} - \cfrac{x^{11}}{11!} + \cfrac{x^{13}}{13!} - \cdots \right |$, does not exceed a term proportional to $x^{9}$. It was also possible to write

$$
\sin x = x - \cfrac{x^{3}}{3!} + \cfrac{x^{5}}{5!} - \cfrac{x^{7}}{7!} + \mathcal{O} (x^{8})
$$

because $\mathcal{O} (x^{9})$ is (much) smaller than terms proportional to $x^{8}$ when $x \sim 0$.
